name: secret CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: use secret
        run: echo "The secret is ${{ secrets.MY_SECRET }}"  

      - name: use secret as env var
        env: 
          MY_SECRET: ${{ secrets.MY_SECRET }} 
        run: echo "The secret is $MY_SECRET"   