name: Custom Actions CI

on: [push]

jobs:
  build: 
    runs-on:

    steps:
      - name: checkout code
      - uses: actions/checkout@v2

      - name: hello world custom action
        uses: munaai/custom-actions@main
        with: 
          who-to-greet: 'Coderco Team'